services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - victoria-o11y-lab

  app-migrate:
    build:
      context: .
      dockerfile: docker/app/migrate.dockerfile
    env_file:
      - .env
    environment:
      MIGRATE_LOG__FORMAT: json
      MIGRATE_LOG__LEVEL: info
      MIGRATE_LOG__ADD_SOURCE: true
      MIGRATE_POSTGRES__HOST: postgres
      MIGRATE_POSTGRES__PORT: 5432
      MIGRATE_POSTGRES__USER: postgres
      MIGRATE_POSTGRES__PASSWORD: postgres
      MIGRATE_POSTGRES__DB: postgres
      MIGRATE_POSTGRES__SSL_MODE: disable
    depends_on:
      - postgres
    networks:
      - victoria-o11y-lab

  app-api:
    build:
      context: .
      dockerfile: docker/app/api.dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      API_LOG__FORMAT: json
      API_LOG__LEVEL: info
      API_LOG__ADD_SOURCE: true
      API_HTTP__PORT: 8000
      API_HTTP__SWAGGER_ENABLED: true
      API_POSTGRES__HOST: postgres
      API_POSTGRES__PORT: 5432
      API_POSTGRES__USER: postgres
      API_POSTGRES__PASSWORD: postgres
      API_POSTGRES__DB: postgres
      API_POSTGRES__SSL_MODE: disable
      API_OTEL__SERVICE_NAME: victoria-o11y-lab-api
      API_OTEL__COLLECTOR_URL: vector:4317
      API_OTEL__INSECURE: true
      API_OTEL__TRACE_ID_RATIO: 1.0
    depends_on:
      - postgres
    networks:
      - victoria-o11y-lab

volumes:
  pg-data:

networks:
  victoria-o11y-lab:
    driver: bridge
