http:
  port: 8000
  swagger_enabled: true

log:
  format: text
  level: debug
  add_source: false

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db: postgres
  ssl_mode: disable
  max_conns: 50
  min_conns: 5
  max_conn_lifetime: 30m
  max_conn_idle_time: 5m

otel:
  service_name: victoria-o11y-lab-api
  # If collector_url is empty, a no-op OTEL SDK will be used.
  collector_url: ""
  insecure: true
  trace_id_ratio: 0.1
  collector_auth: ""
